version: '3'
services:
  mongodb:
    restart: always
    image: mongo:4
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=course
      - MONGO_INITDB_ROOT_USERNAME=course
      - MONGO_INITDB_ROOT_PASSWORD=course2123
    volumes:
      - ./data/db:/data/db