version: '3'
services:
  mongodb:
    restart: always
    image: mongo:4
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=shop
      - MONGO_INITDB_ROOT_USERNAME=shop
      - MONGO_INITDB_ROOT_PASSWORD=shop2123
    volumes:
      - ./data/db:/data/db
  express:
    restart: always
    build: 
      context: ./../
      dockerfile: ./docker/sources/Dockerfile.express
    container_name: express
    environment: 
      - 'NODE_ENV=production'
      - 'DB_URL=mongodb://shop:shop2123@192.168.0.6:27017/shop?authSource=admin'
      - 'PORT=3000'
      - 'STRIPE_KEY=sk_test_51HzL5HJ9TaLfhvGNl04uWHoupyEhBVM9uuzvLDbSur9F0MmHrFh3m2yymQi44Y0HpyZaBJ2SYq7Rcf2cGrAfUWY000Gx0hFP9w'
    ports:
      - 3000:3000